require('config.lazy')
-- require('lsp')
require('options')
require('keymaps')
require('colorscheme')
-- plugins
require('plugins.todo')
require('plugins.telescope')
require('plugins.lsp')
require('plugins.markdown')
require('plugins.neotree')
require('plugins.dashboard')
